import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const cooper = localFont({
  src: [
    {
      path: "../../public/fonts/CooperMdBT-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-cooper",
  display: "swap",
});

export const metadata: Metadata = {
  title: "BehavAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={`${inter.variable} ${cooper.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
